ENT.Base 			= "npc_vj_creature_base"
ENT.Type 			= "ai"
ENT.PrintName 		= "Horror"
ENT.Author 			= "An average Beanmann"
ENT.Contact 		= ""
ENT.Purpose 		= "AAAAAAAAAAA"
ENT.Instructions 	= "AAAAAAAAAAA"
ENT.Category		= "Bean's Little Box of Horrors"